export default function UseCaseDelivery() {
  return (
    <div className="w-full bg-white">
      {/* ================================================= */}
      {/* HEADER */}
      {/* ================================================= */}
      <section className="bg-[#1f2d3d] text-white py-10">
        <h1 className="text-center text-3xl font-semibold">Use Case Delivery</h1>
      </section>

      {/* ================================================= */}
      {/* SECTION 3 */}
      {/* ================================================= */}
      <section className="max-w-7xl mx-auto px-6 py-10">
        <p className="mb-8">
          <strong>From Pilot to Production: Realizing Tangible AI Value</strong> Most AI projects fail because they exist in a vacuum. Our Use Case Delivery service
          ensures that every solution we build is not just a "cool demo," but a production-ready asset. We bridge the gap between business intent
          and technical reality by deploying high-impact applications that simultaneously strengthen your <b>Knowledge Graph</b> and <b>Context
          Engineering layers.</b>

        </p>
        <div className="grid md:grid-cols-2 gap-10 items-start">
          <img
            src="/service3.png"
            alt="Use Case Delivery"
            className="w-full h-auto rounded-3xl shadow-2xl"
          />

          <ul className="list-disc ml-6 space-y-4">
            <li>
              <strong>Strategic Use Case Discovery:</strong> We don't build for the sake of building. We
identify "High-Value, Low-Complexity" opportunities that align with your
strategic ROI goals, ensuring early wins that build organizational momentum.
            </li>
            <li>
              <strong>Context-Aware Development:</strong> Unlike generic AI implementations, our use
cases are built directly on top of your semantic data layer. This ensures the
output is grounded in your specific business logic, reducing hallucinations and
increasing user trust.​
            </li>
            <li>
              <strong>End-to-End Build & Deployment:</strong> FWe manage the full lifecycle—from prompt
engineering and model selection to API integration and UI/UX design. We
move your ideas out of the "sandbox" and into the hands of your employees
or customers.​
            </li>
            <li>
              <strong>Knowledge Loop Integration:</strong> EEvery use case we deploy is designed to "feed
the brain." We establish feedback loops where the data generated by the use
case enriches your Enterprise Knowledge Graph, making the next use case
faster and cheaper to build.​
            </li>
            <li>
              <strong>Scalable AI Orchestration:</strong> We implement the necessary "plumbing"—
including LLM Ops, security guardrails, and cost-monitoring tools—so your
solution is robust, secure, and sustainable at scale.​
            </li>
          </ul>
        </div>
      </section>

      {/* ================================================= */}
{/* ENGAGEMENT MODELS */}
{/* ================================================= */}
<section className="max-w-7xl mx-auto px-6 py-7">
  <div className="border-2 border-gray-800 rounded-3xl p-10">
    <h3 className="text-2xl font-bold mb-8">
      The "Dual-Value" Approach
    </h3>

 <h3 className="text-xl font-bold mb-6">
             When you partner with us for Use Case Delivery, you get two results for the price of one:
            </h3>

            <ul className="list-disc ml-6 space-y-4">
              <li>
                <strong>Immediate Impact:</strong>  A working AI solution that solves a specific pain point (e.g., automated underwriting, intelligent customer support, or
predictive supply chain analysis).
              </li>

              <li>
                <strong>Long-Term Asset:</strong> A more mature data foundation. By establishing the "Context Engineering" infrastructure during the build, we leave your
enterprise more "AI-ready" than we found it.
              </li>
              </ul>
  </div>
</section>

<section className="text-center py-1">
<a href="/contact">
  <button className="inline-flex items-center gap-2 bg-[#0A6190] hover:bg-[#084C6B] text-white px-10 py-4 rounded-lg font-medium transition">
    Talk to Experts
  </button>
</a>
</section>
    </div>
  );
}
